name: 'Log Pruner'
description: 'Delete logs that are older than 7 days.'
author: 'HoseaCodes'

inputs:
  mongodb_url:
    description: 'Mongodb url'
    required: true
  db_name:
    description: 'Database name'
    required: true
  collection_name:
    description: 'Collection name'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'